name: "Tests"
on:
  push:
    branches:
      - main
      - dev
jobs:
  unit_test:
    runs-on: ubuntu-20.04
    steps:
      - name: Echo
        run: |
          echo Welcome to the Github Actions Workshop!