name: "Tests"
on: pull_request
jobs:
  unit-test:
    runs-on: ubuntu-20.04
    container:
      image: epitechcontent/epitest-docker
    steps:
      - uses: actions/checkout@v2
      - name: "Start unittest"
        run: |
          make re
          make tests_run
          make coverage
          ./functional-test.sh
