name: "Tests"
on:
  push:
    branches:
      - main
      - dev
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: "Echo"
        run: |
          echo Welcome to the Github Actions Workshop!
  unit-test:
    runs-on: ubuntu-20.04
    container:
      image: epitechcontent/epitest-docker
    steps:
      - uses: actions/checkout@v2
      - name: "Start unittest"
        run: |
          make re
          make tests_run
          make coverage
          ./functionnal-test.sh
